schedules:
  - cron: '0 20 * * *'
    displayName: Nightly Build
    branches:
      include:
        - dev
    always: true

trigger:
  batch: true
  branches:
    include:
      - dev
      - release/* # azure-functions-java-worker github repo restricts creation of release/* branches, so using a pattern is safe here.

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

variables:
  - template: ci/variables/build.yml@eng
  - template: ci/variables/cfs.yml@eng

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    stages:
      - stage: Build
        templateContext:
          sdl:
            codeql:
              language: java,powershell
              runSourceLanguagesInSourceAnalysis: true
              buildIdentifier: java_worker_official
              excludePathPatterns: '/extract/inst'
        jobs:
          - template: /eng/ci/templates/official/jobs/build-artifacts.yml@self

      - stage: TestWindows
        dependsOn: Build
        templateContext:
          sdl:
            codeql:
              language: csharp
              buildIdentifier: java_worker_csharp_official
              excludePathPatterns: '/extract/inst'
        jobs:
          - template: /eng/ci/templates/official/jobs/run-e2e-tests-windows.yml@self

      - stage: TestLinux
        dependsOn:
          - TestWindows
        templateContext:
          sdl:
            codeql:
              compiled:
                enabled: false
                justificationForDisabling: 'Running the scan in TestWindows stage'
        jobs:
          - template: /eng/ci/templates/official/jobs/run-e2e-tests-linux.yml@self
