schedules:
  - cron: '0 0 * * *'
    displayName: Nightly Build
    branches:
      include:
        - dev
    always: true

trigger:
  batch: true
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - dev

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

    stages:
      - stage: Build
        templateContext:
          sdl:
            codeql:
              language: java,powershell
              buildIdentifier: java_worker_public
              runSourceLanguagesInSourceAnalysis: true
        jobs:
          - template: /eng/ci/templates/jobs/build.yml@self

      - stage: TestWindows
        dependsOn: Build
        templateContext:
          sdl:
            codeql:
              language: csharp
              buildIdentifier: java_worker_csharp_public
              excludePathPatterns: '/extract/inst'
        jobs:
          - template: /eng/ci/templates/jobs/run-emulated-tests-windows.yml@self

      - stage: TestLinux
        dependsOn:
          - TestWindows
        templateContext:
          sdl:
            codeql:
              compiled:
                enabled: false
                justificationForDisabling: 'Running the scan in TestWindows stage'
        jobs:
          - template: /eng/ci/templates/jobs/run-emulated-tests-linux.yml@self
