schedules:
  - cron: '0 0 * * *'
    displayName: Nightly Build
    branches:
      include:
        - dev
    always: true

trigger:
  batch: true
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - dev

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

variables:
  - name: codeql.language
    value: java,powershell
  - name: codeql.buildIdentifier
    value: java_worker_public
  - name: codeql.excludePathPatterns
    value: extract/inst

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

    stages:
      - stage: Build
        jobs:
          - template: /eng/ci/templates/jobs/build.yml@self

      - stage: TestWindows
        dependsOn: Build
        jobs:
          - template: /eng/ci/templates/jobs/run-emulated-tests-windows.yml@self

      - stage: TestLinux
        dependsOn:
          - TestWindows
        jobs:
          - template: /eng/ci/templates/jobs/run-emulated-tests-linux.yml@self
